import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'

export default function Home() {
  return (
    <div>
      <Head>
        <title>PVR</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Banner />
      <main>
        <section className='py-10 bg-[#1B1B1B]'>
          <LargeCard />
        </section>
        <section className='py-10 bg-[#1B1B1B]'>
          <div className='md:mx-4 px-12 md:px-8'>
            <div className='flex justify-between'>
              <div>
              <h2 className='text-white text-2xl pb-10'>NOW SHOWING</h2>
              </div>
              <div className='hidden md:flex items-center space-x-8 text-white text-lg md:px-12'>
                <h2 className='cursor-pointer'>Genre</h2>
                <h2 className='cursor-pointer'>Format</h2>
                <h2 className='cursor-pointer'>Language</h2>
              </div>
            </div>
            <div className='grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-y-8'>
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
            </div>
          </div>
        </section>
        <section className='py-10 bg-[#1B1B1B]'>
          <div className='md:mx-4 px-12 md:px-8'>
            <h2 className='text-white text-2xl pb-10'>COMING SOON</h2>
            <div className='grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-y-8'>
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
              <MediumCard />
            </div>
          </div>
        </section>
      </main>
      {/* footer */}
      <Footer />
        
    </div>
  )
}
